Repository milieuinfo/webcomponent-vl-ui-link-list, pull requests merged in 2020-06, with the labels that each got.

#76 Upgrade dependencies zodat de testen terug werken
  .eslintrc.json
  CODEOWNERS
  demo/demo.js
  index.js
  package-lock.json
  package.json
  src/index.js
  src/vl-link-list.js
  test/e2e/components/vl-link-list.js
  test/e2e/link-list.test.js
  test/e2e/pages/vl-link-list.page.js
  test/unit/vl-link-list.test.html
Labels: bugfix

#77 Upgrade dependencies zodat de testen terug werken
  .eslintrc.json
  dist/vl-link-list.js
  dist/vl-link-list.src.js
  package-lock.json
  package.json
  test/unit/vl-link-list.test.html
Labels: bugfix

#78 Introductie vl-ui-demo en ESlint
  demo/vl-link-list.html
  package-lock.json
  package.json
  src/vl-link-list.js
  test/unit/vl-link-list.test.html
Labels: chore

#81 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
Labels: bug

#83 Deduplicatie NPM run scripts
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
