Repository milieuinfo/webcomponent-vl-ui-link-list, pull requests merged in 2020-03, with the labels that each got.

#61 Toevoegen e2e testen
  demo/vl-link-list.html
  test/e2e/components/vl-link-list.js
  test/e2e/link-list.test.js
  test/e2e/pages/vl-link-list.page.js
Labels: chore

#62 Upate vl-ui-util voor ondersteuning double en single quotes imports
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: bug

#63 Update vl-ui-util
  package-lock.json
  package.json
Labels: chore, maintenance

#64 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore

#65 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore
