Repository milieuinfo/webcomponent-vl-ui-link-list, pull requests merged in 2020-01, with the labels that each got.

#50 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#46 Initiele opzet
  .gitignore
  .mocharc.js
  index.js
  package-lock.json
  package.json
  test/e2e/components/vl-link-list.js
  test/e2e/link-list.test.js
  test/e2e/pages/vl-link-list.page.js
  test/unit/vl-link-list.test.html
  test/wct.docker.conf.json
Labels: chore

#51 Update util
  package-lock.json
  package.json
Labels: bugfix

#52 Overbodig NPM release import scripts verwijderd
  package.json
  style.css
  vl-link-list.js
Labels: maintenance

#54 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#53 Update vl-ui-util
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#55 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#56 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
